# fly.toml app configuration file generated for fusion-demo on 2025-03-14T11:38:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fusion-demo'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
